apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: govinds1209/service-user
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: microservices
spec:
  selector:
    app.kubernetes.io/name: user
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 30002
  type: NodePort
